### ISSUE TITLE
Possibility of supporting xlib?

### ISSUE THREAD

**Issue by parkerlreed** [andohuman/pyWinKey#1]
Thanks for the project. By far the newest and works great!

I have it implemented in a barcode scanning project to input text to the computer. While not significant, I find the subprocess call to xdotool slower than some older xlib solutions (https://github.com/moses-palmer/pynput for example)

Any possibility of having the input handled in library rather than a subprocess call?

**Comment by gauthsvenkat** [comment]
Oh my god, I'm very sorry for this late response. I never really expected people to start using the library, much less someone raising an issue. Weirdly I never got any notification that an issue was raised.

I'm happy that you were able to use it in your project! But unfortunately, I only put this as a package for my own convenience and use, without much thought into developing it in the future. So I'm sorry to say that there won't be much in the name of development in the future. However, if you ever do plan on developing the library, please feel free to issue a pull request.

**Comment by parkerlreed** [comment]
Thanks for the reply! Heh. To be honest I completely forgot as well.

If I ever come back to that project, I may take a stab at updating it.
